name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-24.04

    services:
      altertable:
        image: ghcr.io/altertable-ai/altertable-mock:latest
        ports:
          - 15000:15000
        env:
          ALTERTABLE_MOCK_USERS: testuser:testpass
        options: >-
          --health-cmd "exit 0"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
          --health-start-period 10s

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
